# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'GeneralConnect' do
pod 'ProgressHUD', '~> 2.3'
pod 'AFNetworking', '~> 3.0.4'
pod 'MJExtension', '~> 3.0.10'
end

target 'GeneralConnectTests' do

end

target 'GeneralConnectUITests' do

end

